name: Create Entra Security Group

on:
  workflow_dispatch:
    inputs:
      group_name:
        description: 'Security Group Name'
        required: true
        default: 'Test-Group'

permissions:
  id-token: write

jobs:
  create-group:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get token via OIDC
        id: get-token
        shell: pwsh
        run: |
          $token = Invoke-RestMethod `
            -Uri $env:ACTIONS_ID_TOKEN_REQUEST_URL `
            -Headers @{ "Authorization" = "bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN" } | Select-Object -ExpandProperty token
          
          echo "oidc_token=$token" >> $env:GITHUB_OUTPUT
